// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvljtUz6HUnUbxO8Ra60RRWhak-Vm2dFw',
    appId: '1:207963067009:web:6186313175ed1ae350f380',
    messagingSenderId: '207963067009',
    projectId: 'iot-43c2f',
    authDomain: 'iot-43c2f.firebaseapp.com',
    storageBucket: 'iot-43c2f.appspot.com',
    measurementId: 'G-G0Z0VBJHP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7XrJpW-SGdb8W4ddN8C6wxsCnpyWcGqc',
    appId: '1:207963067009:android:a537f3f59218135450f380',
    messagingSenderId: '207963067009',
    projectId: 'iot-43c2f',
    storageBucket: 'iot-43c2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu4epqJkFwIL8OtlpWltUaIIIru3Gtwn8',
    appId: '1:207963067009:ios:06c90862cbcf8aca50f380',
    messagingSenderId: '207963067009',
    projectId: 'iot-43c2f',
    storageBucket: 'iot-43c2f.appspot.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu4epqJkFwIL8OtlpWltUaIIIru3Gtwn8',
    appId: '1:207963067009:ios:06c90862cbcf8aca50f380',
    messagingSenderId: '207963067009',
    projectId: 'iot-43c2f',
    storageBucket: 'iot-43c2f.appspot.com',
    iosBundleId: 'com.example.grocery',
  );
}
