// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcayFLIUmLDDK2j47aoDl-Mtq4uEBjCCk',
    appId: '1:310952800025:web:2908f5df3b361948969f88',
    messagingSenderId: '310952800025',
    projectId: 'flutter-indi-84de1',
    authDomain: 'flutter-indi-84de1.firebaseapp.com',
    storageBucket: 'flutter-indi-84de1.appspot.com',
    measurementId: 'G-BD3Y68XJ5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJR2ll5oGAtsPN3tqgSftEq1lojlTptaU',
    appId: '1:310952800025:android:c6bf3d21a9b7c5d0969f88',
    messagingSenderId: '310952800025',
    projectId: 'flutter-indi-84de1',
    storageBucket: 'flutter-indi-84de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocF6UpwE39yaOJRaqcQvCwdzbxoFwBJg',
    appId: '1:310952800025:ios:5d292541eed1acdd969f88',
    messagingSenderId: '310952800025',
    projectId: 'flutter-indi-84de1',
    storageBucket: 'flutter-indi-84de1.appspot.com',
    iosClientId: '310952800025-nessk6mbd5fq274c2mahpdnppq5v8s5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCocF6UpwE39yaOJRaqcQvCwdzbxoFwBJg',
    appId: '1:310952800025:ios:5d292541eed1acdd969f88',
    messagingSenderId: '310952800025',
    projectId: 'flutter-indi-84de1',
    storageBucket: 'flutter-indi-84de1.appspot.com',
    iosClientId: '310952800025-nessk6mbd5fq274c2mahpdnppq5v8s5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.grocery',
  );
}
